---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by HP.
--- DateTime: 03.12.2024 07:40
---

level = {
    assets = {
        --- force start at zero index
        [0] = {

        }

    },
    tilemap = {

    },
    entities = {
        [0] = {

        },
    }
}